"""Add game_user Association Table

Revision ID: 033de4b90e01
Revises: a28af33e6866
Create Date: 2023-12-11 16:44:39.277002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033de4b90e01'
down_revision = 'a28af33e6866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
